title: Lee Seung Jun
description: A minimal and beautiful Jekyll theme best for writing and note-taking.
author: 이승준
avatar: /승준.png
email: xotmd1002@gmail.com
logo: 승준.png
social:
  name: 승준
  links:
    - https://www.instagram.com/s_zuno.o
    - https://mooto2002.github.io/
lang: ko
